

//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All


namespace Systems.Charon
{
	using System;
	using System.Linq;
	using System.IO;
	using System.Text;
	using System.Globalization;
	using System.Collections;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.CodeDom.Compiler;
	using System.Runtime.InteropServices;
	using System.Runtime.CompilerServices;
	using System.Linq.Expressions;
	using System.Threading;
	using System.Reflection;
	using System.Diagnostics;


	public sealed partial class DocumentReference<DocumentT> where DocumentT : Document
	{
		private readonly string schemaIdOrName;
		[NonSerialized]
		private DocumentT document;
		[NonSerialized]
		private readonly Func<string, object, Document> findFunc;

		public object Id { get; }

		public DocumentReference(object id, string schemaIdOrName, Func<string, object, Document> findFunc)
		{
			if (id == null) throw new ArgumentNullException(nameof(id));
			if (findFunc == null) throw new ArgumentNullException(nameof(findFunc));

			this.schemaIdOrName = schemaIdOrName;
			this.findFunc = findFunc;
			this.Id = id;
		}

		public DocumentT Dereference()
		{
			if (this.document != null)
			{
				return this.document;
			}

			return this.document = (DocumentT)this.findFunc(this.schemaIdOrName, this.Id);
		}

		public static implicit operator DocumentT(DocumentReference<DocumentT> reference)
		{
			return reference.Dereference();
		}

		public override bool Equals(object value)
		{
			if (!(value is DocumentReference<DocumentT> other))
			{
				return false;
			}
			else if (ReferenceEquals(this, value))
			{
				return true;
			}

			return Equals(this.Id, other.Id);
		}

		public override int GetHashCode()
		{
			var hashCode = this.Id != null ? this.Id.GetHashCode() : 0;
			return hashCode;
		}

		public override string ToString()
		{
			return $"Id: {this.Id}, Schema: {this.schemaIdOrName}, Resolved: {this.document != null}";
		}
	}

}
