

//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All


namespace Systems.Charon
{
	using System;
	using System.Linq;
	using System.IO;
	using System.Text;
	using System.Globalization;
	using System.Collections;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.CodeDom.Compiler;
	using System.Runtime.InteropServices;
	using System.Runtime.CompilerServices;
	using System.Linq.Expressions;
	using System.Threading;
	using System.Reflection;
	using System.Diagnostics;


	[Serializable, DebuggerDisplay("DocumentCollection, Count: {" + nameof(Count) + "}")]
	public partial class DocumentCollection<KeyT, DocumentT> : IReadOnlyDictionary<KeyT, DocumentT>, IEquatable<DocumentCollection<KeyT, DocumentT>> where DocumentT : Document
	{
		public static readonly DocumentCollection<KeyT, DocumentT> Empty = new DocumentCollection<KeyT, DocumentT>(Array.Empty<DocumentT>(), new Dictionary<KeyT, DocumentT>(), new Dictionary<Delegate, object>());

		private readonly IReadOnlyList<DocumentT> documents;
		private readonly IReadOnlyDictionary<KeyT, DocumentT> documentsByKey;
		private readonly Dictionary<Delegate, object> byPropertyDictionary;

		public IReadOnlyList<DocumentT> AsList => this.documents;
		/// <inheritdoc />
		public DocumentT this[KeyT key] => this.documentsByKey[key];
		/// <inheritdoc />
		public IEnumerable<KeyT> Keys => this.documentsByKey.Keys;
		/// <inheritdoc />
		public IEnumerable<DocumentT> Values => this.documentsByKey.Values;
		/// <inheritdoc />
		public int Count => this.documentsByKey.Count;

		private DocumentCollection(IReadOnlyList<DocumentT> documents, IReadOnlyDictionary<KeyT, DocumentT> documentsByKey, Dictionary<Delegate, object> byPropertyDictionary)
		{
			if (documents == null) throw new ArgumentNullException(nameof(documents));
			if (documentsByKey == null) throw new ArgumentNullException(nameof(documentsByKey));
			if (byPropertyDictionary == null) throw new ArgumentNullException(nameof(byPropertyDictionary));

			this.documents = documents;
			this.documentsByKey = documentsByKey;
			this.byPropertyDictionary = byPropertyDictionary;
		}
		public DocumentCollection(IEnumerable<DocumentT> documents, Func<DocumentT, KeyT> selectKeyFunc, IEqualityComparer<KeyT> idComparer = default)
		{
			if (documents == null) throw new ArgumentNullException(nameof(documents));
			if (selectKeyFunc == null) throw new ArgumentNullException(nameof(selectKeyFunc));

			this.documents = documents as IReadOnlyList<DocumentT> ?? documents.ToList();
			var documentByKey = new Dictionary<KeyT, DocumentT>(this.documents.Count, idComparer ?? EqualityComparer<KeyT>.Default);
			foreach (var document in this.documents)
			{
				if (document == null)
				{
					continue;
				}

				var key = selectKeyFunc(document);
				if (ReferenceEquals(key, null))
				{
					continue;
				}

				documentByKey[key] = document;
			}

			this.documentsByKey = documentByKey;
			this.byPropertyDictionary = new Dictionary<Delegate, object> {
				{ selectKeyFunc, this }
			};
		}

		/// <inheritdoc />
		IEnumerator<KeyValuePair<KeyT, DocumentT>> IEnumerable<KeyValuePair<KeyT, DocumentT>>.GetEnumerator()
		{
			return this.documentsByKey.GetEnumerator();
		}
		/// <inheritdoc />
		IEnumerator IEnumerable.GetEnumerator()
		{
			return ((IEnumerable)this.documentsByKey).GetEnumerator();
		}

		/// <inheritdoc />
		public bool ContainsKey(KeyT key)
		{
			return this.documentsByKey.ContainsKey(key);
		}
		/// <inheritdoc />
		public bool TryGetValue(KeyT key, out DocumentT value)
		{
			return this.documentsByKey.TryGetValue(key, out value);
		}

		public DocumentT Get(KeyT key)
		{
			if (!this.TryGetValue(key, out var document))
			{
				throw new ArgumentException($"Unable find {typeof(DocumentT).Name} with one of unique attributes equals to '{key}'.",nameof(key));
			}
			return document;
		}
		public DocumentT Find(KeyT key)
		{
			this.TryGetValue(key, out var document);
			return document;
		}

		[Obsolete("Use ByKey() method due better semantic. This method will be removed after 01.01.2024")]
		public DocumentCollection<NewKeyT, DocumentT> WithOtherKey<NewKeyT>(Func<DocumentT, NewKeyT> selectKeyFunc, IEqualityComparer<NewKeyT> keyComparer = default)
		{
			return this.ByKey(selectKeyFunc, keyComparer);
		}
		public DocumentCollection<NewKeyT, DocumentT> ByKey<NewKeyT>(Func<DocumentT, NewKeyT> selectKeyFunc, IEqualityComparer<NewKeyT> keyComparer = default)
		{
			if (selectKeyFunc == null) throw new ArgumentNullException(nameof(selectKeyFunc));

			if (this.Count == 0)
			{
				return DocumentCollection<NewKeyT, DocumentT>.Empty;
			}

			lock (this.byPropertyDictionary)
			{
				if (this.byPropertyDictionary.TryGetValue(selectKeyFunc, out var documentCollectionObj) &&
					documentCollectionObj is DocumentCollection<NewKeyT, DocumentT> existingDocumentCollection)
				{
					return existingDocumentCollection;
				}
			}

			var newDocumentByKey = new Dictionary<NewKeyT, DocumentT>(keyComparer ?? EqualityComparer<NewKeyT>.Default);
			foreach (var document in this.documents)
			{
				if (document == null)
				{
					continue;
				}

				var key = selectKeyFunc(document);
				if (ReferenceEquals(key, null))
				{
					continue;
				}

				newDocumentByKey[key] = document;
			}

			lock (this.byPropertyDictionary)
			{
				var newDocumentCollection = new DocumentCollection<NewKeyT, DocumentT>(this.documents, newDocumentByKey, this.byPropertyDictionary);
				this.byPropertyDictionary[selectKeyFunc] = newDocumentCollection;
				return newDocumentCollection;
			}
		}

		public IEnumerator<DocumentT> GetEnumerator()
		{
			return this.documents.GetEnumerator();
		}

		/// <inheritdoc />
		public bool Equals(DocumentCollection<KeyT, DocumentT> other)
		{
			if (ReferenceEquals(null, other)) return false;
			if (ReferenceEquals(this, other)) return true;

			return this.documents.SequenceEqual(other.documents);
		}
		/// <inheritdoc />
		public override bool Equals(object obj)
		{
			if (ReferenceEquals(null, obj)) return false;
			if (ReferenceEquals(this, obj)) return true;
			if (obj.GetType() != this.GetType()) return false;

			return this.Equals((DocumentCollection<KeyT, DocumentT>)obj);
		}
		/// <inheritdoc />
		public override int GetHashCode()
		{
			return this.documents.Aggregate(0, (acc, next) => unchecked(next.GetHashCode() * 17 + acc));
		}

		/// <inheritdoc />
		public override string ToString()
		{
			return this.documentsByKey.ToString();
		}
	}

}
