

//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All


namespace Systems.Charon
{
	using System;
	using System.Linq;
	using System.IO;
	using System.Text;
	using System.Globalization;
	using System.Collections;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.CodeDom.Compiler;
	using System.Runtime.InteropServices;
	using System.Runtime.CompilerServices;
	using System.Linq.Expressions;
	using System.Threading;
	using System.Reflection;
	using System.Diagnostics;


	[Serializable, DebuggerDisplay("DocumentReferenceCollection, Count: {" + nameof(Count) + "}")]
	public partial class DocumentReferenceCollection<DocumentT>: IReadOnlyList<DocumentReference<DocumentT>>, IEquatable<DocumentReferenceCollection<DocumentT>> where DocumentT : Document
	{
		public static readonly DocumentReferenceCollection<DocumentT> Empty = new DocumentReferenceCollection<DocumentT>(Array.Empty<DocumentReference<DocumentT>>());

		private readonly IReadOnlyList<DocumentReference<DocumentT>> referenceList;
		[NonSerialized]
		private object documentCollectionById;
		[NonSerialized]
		private IReadOnlyList<DocumentT> documentList;

		public DocumentReferenceCollection(IReadOnlyList<DocumentReference<DocumentT>> referenceList)
		{
			if (referenceList == null) throw new ArgumentNullException(nameof(referenceList));

			this.referenceList = referenceList;
		}

		/// <inheritdoc />
		public int Count => this.referenceList.Count;
		/// <inheritdoc />
		public DocumentReference<DocumentT> this[int index] => this.referenceList[index];

		public IReadOnlyList<DocumentT> Dereference()
		{
			if (this.documentList != null)
			{
				return this.documentList;
			}
			var documents = new DocumentT[this.Count];
			for (var i = 0; i < this.referenceList.Count; i++)
			{
				documents[i] = this.referenceList[i].Dereference();
			}
			return this.documentList = documents;
		}
		public DocumentCollection<IdT, DocumentT> Dereference<IdT>(Func<DocumentT, IdT> idSelectFunc)
		{
			if (idSelectFunc == null) throw new ArgumentNullException(nameof(idSelectFunc));

			if (this.documentCollectionById == null && this.Count == 0)
			{
				this.documentCollectionById = DocumentCollection<IdT, DocumentT>.Empty;
			}
			else if((this.documentCollectionById as DocumentCollection<IdT, DocumentT>) == null)
			{
				var documents = this.Dereference();
				this.documentCollectionById = new DocumentCollection<IdT, DocumentT>(documents, idSelectFunc);
			}
			return (DocumentCollection<IdT, DocumentT>)this.documentCollectionById;
		}

		/// <inheritdoc />
		IEnumerator<DocumentReference<DocumentT>> IEnumerable<DocumentReference<DocumentT>>.GetEnumerator()
		{
			return this.referenceList.GetEnumerator();
		}
		/// <inheritdoc />
		IEnumerator IEnumerable.GetEnumerator()
		{
			return ((IEnumerable)this.referenceList).GetEnumerator();
		}
		/// <inheritdoc />
		public bool Equals(DocumentReferenceCollection<DocumentT> other)
		{
			if (ReferenceEquals(null, other)) return false;
			if (ReferenceEquals(this, other)) return true;

			return this.referenceList.SequenceEqual(other.referenceList);
		}
		/// <inheritdoc />
		public override bool Equals(object obj)
		{
			if (ReferenceEquals(null, obj)) return false;
			if (ReferenceEquals(this, obj)) return true;
			if (obj.GetType() != this.GetType()) return false;

			return this.Equals((DocumentReferenceCollection<DocumentT>)obj);
		}
		/// <inheritdoc />
		public override int GetHashCode()
		{
			return this.referenceList.Aggregate(0, (acc, next) => unchecked(next.GetHashCode() * 17 + acc));
		}

		/// <inheritdoc />
		public override string ToString()
		{
			return this.referenceList.ToString();
		}
	}

}
