

//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All


namespace Systems.Charon
{
	using System;
	using System.Linq;
	using System.IO;
	using System.Text;
	using System.Globalization;
	using System.Collections;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.CodeDom.Compiler;
	using System.Runtime.InteropServices;
	using System.Runtime.CompilerServices;
	using System.Linq.Expressions;
	using System.Threading;
	using System.Reflection;
	using System.Diagnostics;


#pragma warning disable 0660, 0661
	public abstract partial class Document
	{
		public Document Parent { get; private set; }

		public static bool operator ==(Document value1, Document value2)
		{
			if (ReferenceEquals(value1, value2)) return true;
			if (ReferenceEquals(value1, null) || ReferenceEquals(value2, null)) return false;

			return Equals(value1, value2);
		}
		public static bool operator !=(Document value1, Document value2)
		{
			if (ReferenceEquals(value1, value2)) return false;
			if (ReferenceEquals(value1, null) || ReferenceEquals(value2, null)) return true;

			return Equals(value1, value2) == false;
		}

		protected static void SetParent(Document document, Document parent)
		{
			if (ReferenceEquals(document, null)) return;

			document.Parent = parent;
		}

		protected static bool AreEquals<T>(T value1, T value2)
		{
			return EqualityComparer<T>.Default.Equals(value1, value2);
		}
		protected static int GetHashCodeFor<T>(T value)
		{
			return EqualityComparer<T>.Default.GetHashCode(value);
		}
	}
#pragma warning restore 0660, 0661

}
