

//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All


namespace Systems.Charon
{
	using System;
	using System.Linq;
	using System.IO;
	using System.Text;
	using System.Globalization;
	using System.Collections;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.CodeDom.Compiler;
	using System.Runtime.InteropServices;
	using System.Runtime.CompilerServices;
	using System.Linq.Expressions;
	using System.Threading;
	using System.Reflection;
	using System.Diagnostics;

	[GeneratedCode(GameData.GeneratorName, GameData.GeneratorVersion)]
	public partial class GameData
	{
		public const string GeneratorName = "Charon";
		public const string GeneratorVersion = "2025.4.2.0";

		private class DocumentCollections
		{
			public DocumentCollection<System.String,ProjectSetting> ProjectSettingsList = DocumentCollection<System.String,ProjectSetting>.Empty;
		}

		#region Formula fields
		public static readonly Type[] FormulaTypes = new Type[]
		{
				typeof(GameData),
				typeof(ProjectSetting),
		};
#if USE_DYNAMIC_EXPRESSIONS
		public static readonly GameDevWare.Dynamic.Expressions.ITypeResolver TypeResolver = new GameDevWare.Dynamic.Expressions.KnownTypeResolver(FormulaTypes);
#elif !SUPPRESS_BUILD_IN_FORMULAS
		public static readonly Formulas.IFormulaTypeResolver TypeResolver = new Formulas.KnownFormulaTypeResolver(FormulaTypes, Formulas.FormulaOptions.None);
#endif
		#endregion

		#region Schema collections storage fields
		private readonly DocumentCollections rootDocuments;
		private readonly DocumentCollections allDocuments;
		#endregion

		#region Schema collections
		public ProjectSetting ProjectSettings => this.GetOne<ProjectSetting>(this.rootDocuments.ProjectSettingsList.AsList);
		#endregion

		private ReadOnlyCollection<String> languages;
		private LocalizedText.LanguageSwitcher languageSwitcher;
		private int changeNumber;
		private string revisionHash;
		private string gameDataVersion;

		public int ChangeNumber { get { return this.changeNumber; } }
		public string RevisionHash { get { return this.revisionHash; } }
		public string GameDataVersion { get { return this.gameDataVersion; } }
		public ReadOnlyCollection<string> SupportedLanguages { get { return this.languages; } }
		public Func<string, object, Document> FindDocument { get; private set; }


		public GameData(Stream gameDataStream, Formatters.GameDataLoadOptions options)
		{
			if (gameDataStream == null) throw new ArgumentNullException(nameof(gameDataStream));
			if (options == null) throw new ArgumentNullException(nameof(options));

			this.languages = new ReadOnlyCollection<String>(new String[] { "en-US" });
			this.rootDocuments = new DocumentCollections();
			this.allDocuments = new DocumentCollections();
			this.languageSwitcher = new LocalizedText.LanguageSwitcher {
				CurrentLanguageId = "en-US",
				FallbackLanguageId = "en-US",
				PrimaryLanguageId = "en-US",
			};

			this.FindDocument = this.FindDocumentInternal;

			var gameDataReader = this.CreateReader(gameDataStream, options);
			gameDataReader.NextToken();
			var patches = (options.Patches ?? Array.Empty<Stream>());
			if (patches.Count > 0)
			{
				var gameDataDocument = gameDataReader.ReadObject();
				foreach (var patchStream in patches)
				{
					using (var patchReader = this.CreateReader(patchStream, options))
					{
						patchReader.NextToken();
						var patchDocument = patchReader.ReadObject();
						gameDataDocument = this.MergeGameData(gameDataDocument, patchDocument);
					}
				}
				gameDataReader = new Formatters.GameDataObjectReader(gameDataDocument);
				gameDataReader.NextToken();
			}
			try { this.ReadGameData(gameDataReader); }
			finally { gameDataReader.Dispose(); }

			this.FindAllDocuments();
			this.ReadProjectSettings();


#pragma warning disable 0162 // Unreachable code detected
			this.OnInitialize();
#pragma warning restore 0162
		}

		partial void OnInitialize();

		public IEnumerable<Document> GetAllDocuments()
		{
			return this.EnumerateAll();
		}

		public void SetLanguage(string languageId)
		{
			this.SetLanguage(languageId, languageId);
		}
		public void SetLanguage(string languageId, string fallbackLanguageId = "en-US", LocalizedText.FallbackOption fallbackOption = LocalizedText.FallbackOption.OnNull)
		{
			if (languageId == null) throw new ArgumentNullException(nameof(languageId));
			if (fallbackLanguageId == null) throw new ArgumentNullException(nameof(fallbackLanguageId));

			this.languageSwitcher.CurrentLanguageId = languageId;
			this.languageSwitcher.FallbackLanguageId = fallbackLanguageId ?? languageId;
			this.languageSwitcher.FallbackOption = fallbackOption;
		}

		public IEnumerable<string> GetDocumentIds(string schemaNameOrId)
		{
#pragma warning disable 1522 // Empty switch block
			switch (schemaNameOrId)
			{
				case "ProjectSettings":
				case "55a4f32faca22e191098f3d9": return this.allDocuments.ProjectSettingsList.Values.Select(document => ChangeType<string>(document.Id));
			}
#pragma warning restore 1522
			throw new System.ArgumentException(string.Format("Unable find Schema with id '{0}'.", schemaNameOrId) , nameof(schemaNameOrId));
		}

		public IEnumerable<string> GetDocumentSchemaNames()
		{
			yield return "ProjectSettings";
		}

		private DocumentT GetOne<DocumentT>(IReadOnlyCollection<DocumentT> documents) where DocumentT : Document
		{
			switch(documents.Count)
			{
				case 0: throw new InvalidOperationException($"Unable to find '{typeof(DocumentT)}' document. Please create '{typeof(DocumentT)}' document before using this property.");
				case 1: return System.Linq.Enumerable.Single<DocumentT>(documents);
				default: throw new InvalidOperationException($"There are multiple variants of the '{typeof(DocumentT)}' document. Please remove the excess before using this property.");
			}
		}

		private Document FindDocumentInternal(string schemaId, object id)
		{
			if (schemaId == null) throw new ArgumentNullException(nameof(schemaId));

#pragma warning disable 1522 // Empty switch block
			switch (schemaId)
			{
				case "ProjectSettings":
				case "55a4f32faca22e191098f3d9": return this.allDocuments.ProjectSettingsList.Get(ChangeType<System.String>(id));
			}
#pragma warning restore 1522
			throw new System.ArgumentException(string.Format("Unable find Schema with id '{0}'.", schemaId) , nameof(schemaId));
		}

		private IEnumerable<Document> EnumerateAll()
		{
			var i = 0;
			var end = 0;
			var ProjectSettingsList = this.allDocuments.ProjectSettingsList.AsList;
			for (i = 0, end = ProjectSettingsList.Count; i < end; i++)
			{
				yield return ProjectSettingsList[i];
			}
			yield break;
		}

		private IEnumerable<Document> EnumerateRoots()
		{
			var i = 0;
			var end = 0;
			var ProjectSettingsList = this.rootDocuments.ProjectSettingsList.AsList;
			for (i = 0, end = ProjectSettingsList.Count; i < end; i++)
			{
				yield return ProjectSettingsList[i];
			}

			yield break;
		}

		private static T ChangeType<T>(object objValue)
		{
			if (objValue is T typeValue)
			{
				return typeValue;
			}
			else if (typeof(T).IsEnum && objValue is string enumValueString)
			{
				return (T)Enum.Parse(typeof(T), enumValueString, ignoreCase: true);
			}
			else if (typeof(T).IsEnum)
			{
				return (T)Enum.ToObject(typeof(T), objValue);
			}
			else if (typeof(T) == typeof(TimeSpan))
			{
				var timeSpanStr = Convert.ToString(objValue, CultureInfo.InvariantCulture);
				return (T)(object)TimeSpan.Parse(timeSpanStr);
			}
			else if (typeof(T) == typeof(DateTime))
			{
				var dateTimeStr = Convert.ToString(objValue, CultureInfo.InvariantCulture);
				return (T)(object)DateTime.ParseExact(dateTimeStr, Formatters.GameDataReader.DateTimeFormats, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind);
			}
			else if (typeof(T) == typeof(DateTimeOffset))
			{
				var dateTimeOffsetStr = Convert.ToString(objValue, CultureInfo.InvariantCulture);
				return (T)(object)DateTimeOffset.ParseExact(dateTimeOffsetStr, Formatters.GameDataReader.DateTimeFormats, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind);
			}
			else
			{
				return (T)Convert.ChangeType(objValue, typeof(T), CultureInfo.InvariantCulture);
			}
		}


		#region Read Game Data

		public Formatters.GameDataReader CreateReader(Stream gameDataStream, Formatters.GameDataLoadOptions options)
		{
			if (gameDataStream == null) throw new ArgumentNullException(nameof(gameDataStream));
			if (options == null) throw new ArgumentNullException(nameof(options));

			switch(options.Format)
			{
				case Formatters.GameDataFormat.Json: return new Formatters.JsonGameDataReader(gameDataStream, leaveOpen: options.LeaveStreamsOpen, useStringPooling: true);
				case Formatters.GameDataFormat.MessagePack: return new Formatters.MessagePackGameDataReader(gameDataStream, leaveOpen: options.LeaveStreamsOpen, useStringPooling: true);
				default: throw new ArgumentException($"Unknown/Unsupported data format specified '{options.Format}'.", nameof(options));
			}
		}

		public void ReadGameData(Formatters.GameDataReader reader)
		{
			if (reader == null) throw new ArgumentNullException(nameof(reader));

			reader.ReadObjectBegin();
			while(reader.Token != Formatters.ReaderToken.EndOfObject)
			{
				var memberName = reader.ReadMember();
				switch(memberName)
				{
					case "ChangeNumber":
						this.changeNumber = (Int32)reader.ValueAsInt32;
						reader.NextToken();
						break;
					case "RevisionHash":
						this.revisionHash = (string)reader.ValueAsString;
						reader.NextToken();
						break;
					case "Collections":
						reader.ReadObjectBegin();
						while(reader.Token != Formatters.ReaderToken.EndOfObject)
						{
							var collectionName = reader.ReadMember();
							switch (collectionName.Length)
							{
								case 15:
									switch(collectionName)
									{
										case "55a4f32faca22e191098f3d9":
										case "ProjectSettings":
										{
											if (reader.IsNull())
											{
												reader.NextToken();
												break;
											}

											this.rootDocuments.ProjectSettingsList = this.ReadProjectSettingsCollection(reader, 1);
											break;
										}
										default:
											reader.SkipAny();
											break;
									}
									break;
								default:
									reader.SkipAny();
									break;
							}
						}
						reader.ReadObjectEnd();
						break;
					default:
						reader.SkipAny();
						break;
				}
			}

			reader.ReadObjectEnd();
		}

		private void ReadProjectSettings()
		{
			var projectSettings = System.Linq.Enumerable.FirstOrDefault(this.rootDocuments.ProjectSettingsList.AsList);
			if (projectSettings == null)
			{
				return;
			}

			this.gameDataVersion = projectSettings?.Version ?? string.Empty;

			if (string.IsNullOrEmpty(projectSettings.Languages))
			{
				return;
			}

			var languages = new List<String>(projectSettings.Languages.Split(";,| ".ToCharArray(), StringSplitOptions.RemoveEmptyEntries));
			if (string.IsNullOrEmpty(projectSettings.PrimaryLanguage) == false)
			{
				this.languageSwitcher.PrimaryLanguageId = projectSettings.PrimaryLanguage;
			}
			else if (languages.Count > 0)
			{
				this.languageSwitcher.PrimaryLanguageId = languages[0];
			}
			else
			{
				this.languageSwitcher.PrimaryLanguageId = "en-US";
			}

			this.languageSwitcher.CurrentLanguageId = this.languageSwitcher.FallbackLanguageId = this.languageSwitcher.PrimaryLanguageId;
			if (!languages.Contains(this.languageSwitcher.PrimaryLanguageId)) {
				languages.Add(this.languageSwitcher.PrimaryLanguageId);
			}
			languages.Sort(StringComparer.OrdinalIgnoreCase);

			this.languages = new ReadOnlyCollection<String>(languages);
		}


		private DocumentCollection<System.String,ProjectSetting> ReadProjectSettingsCollection(Formatters.GameDataReader reader, int capacity = 0)
		{
			if (reader.IsNull())
			{
				return DocumentCollection<System.String,ProjectSetting>.Empty;
			}

			var isByIdCollection = reader.Token == Formatters.ReaderToken.BeginObject;
			var collection = default(List<ProjectSetting>);

			if (isByIdCollection)
			{
				reader.ReadObjectBegin();
			}
			else
			{
				reader.ReadArrayBegin();
			}
			while (reader.Token != Formatters.ReaderToken.EndOfArray &&
					reader.Token != Formatters.ReaderToken.EndOfObject)
			{
				if (isByIdCollection)
				{
					var _ = reader.ReadMember(); // skip id
				}

				if (reader.IsNull())
				{
					reader.NextToken();
					continue;
				}

				var document = this.ReadProjectSettings(reader);
				if (collection == null)
				{
					collection = new List<ProjectSetting>(capacity > 0 ? capacity : 10);
				}

				collection.Add(document);
			}
			if (isByIdCollection)
			{
				reader.ReadObjectEnd();
			}
			else
			{
				reader.ReadArrayEnd();
			}

			if (collection == null)
			{
				return DocumentCollection<System.String,ProjectSetting>.Empty;
			}
			else
			{
				return new DocumentCollection<System.String,ProjectSetting>(collection, document => document.Id);
			}
		}

		private ProjectSetting ReadProjectSettings(Formatters.GameDataReader reader)
		{
#pragma warning disable 0168 // The variable is declared but never used
			var _id__ = default(System.String);
			var _name__ = default(System.String);
			var _primaryLanguage__ = default(System.String);
			var _languages__ = default(System.String);
			var _copyright__ = default(System.String);
			var _version__ = default(System.String);
			var _extensions__ = default(System.String);
#pragma warning restore 0168
			reader.ReadObjectBegin();
			while (reader.Token != Formatters.ReaderToken.EndOfObject)
			{
				var propertyName = reader.ReadMember();
				switch (propertyName.Length)
				{
					case 2:
					{
						switch (propertyName)
						{
							case "Id":
							{
								reader.ThrowIfNull("value of Text type", "Id", "ProjectSettings");
								reader.ThrowIfNotValue();

								_id__ = (System.String)reader.ValueAsString;
								reader.NextToken();
								break;
							}
							default:
							{
								reader.SkipAny();
								break;
							}
						}
						break;
					}
					case 4:
					{
						switch (propertyName)
						{
							case "Name":
							{
								reader.ThrowIfNull("value of Text type", "Name", "ProjectSettings");
								reader.ThrowIfNotValue();

								_name__ = (System.String)reader.ValueAsString;
								reader.NextToken();
								break;
							}
							default:
							{
								reader.SkipAny();
								break;
							}
						}
						break;
					}
					case 7:
					{
						switch (propertyName)
						{
							case "Version":
							{
								reader.ThrowIfNull("value of Text type", "Version", "ProjectSettings");
								reader.ThrowIfNotValue();

								_version__ = (System.String)reader.ValueAsString;
								reader.NextToken();
								break;
							}
							default:
							{
								reader.SkipAny();
								break;
							}
						}
						break;
					}
					case 9:
					{
						switch (propertyName)
						{
							case "Languages":
							{
								if (reader.IsNull())
								{
									reader.NextToken();
									continue;
								}
								reader.ThrowIfNotValue();

								_languages__ = (System.String)reader.ValueAsString;
								reader.NextToken();
								break;
							}
							case "Copyright":
							{
								if (reader.IsNull())
								{
									reader.NextToken();
									continue;
								}
								reader.ThrowIfNotValue();

								_copyright__ = (System.String)reader.ValueAsString;
								reader.NextToken();
								break;
							}
							default:
							{
								reader.SkipAny();
								break;
							}
						}
						break;
					}
					case 10:
					{
						switch (propertyName)
						{
							case "Extensions":
							{
								if (reader.IsNull())
								{
									reader.NextToken();
									continue;
								}
								reader.ThrowIfNotValue();

								_extensions__ = (System.String)reader.ValueAsString;
								reader.NextToken();
								break;
							}
							default:
							{
								reader.SkipAny();
								break;
							}
						}
						break;
					}
					case 15:
					{
						switch (propertyName)
						{
							case "PrimaryLanguage":
							{
								if (reader.IsNull())
								{
									reader.NextToken();
									continue;
								}
								reader.ThrowIfNotValue();

								_primaryLanguage__ = (System.String)reader.ValueAsString;
								reader.NextToken();
								break;
							}
							default:
							{
								reader.SkipAny();
								break;
							}
						}
						break;
					}
					default:
					{
						reader.SkipAny();
						break;
					}
				}
			}
			reader.ReadObjectEnd();

			var __ProjectSetting = new ProjectSetting(_id__, _name__, _primaryLanguage__, _languages__, _copyright__, _version__, _extensions__);
			return __ProjectSetting;
		}
		private LocalizedText ReadLocalizedText(Formatters.GameDataReader reader)
		{
			var locStringDictionary = default(List<KeyValuePair<string, string>>);
			reader.ReadObjectBegin();
			while(reader.Token != Formatters.ReaderToken.EndOfObject)
			{
				var key = reader.ReadMember();
				var value = reader.ReadAny()?.ToString();
				if (string.IsNullOrEmpty(key) ||
					string.IsNullOrEmpty(value) ||
					string.Equals(key, "notes", StringComparison.Ordinal))
				{
					continue;
				}

				if (locStringDictionary == null)
				{
					locStringDictionary = new List<KeyValuePair<string, string>>(10);
				}
				locStringDictionary.Add(new KeyValuePair<string, string>(key, value));
			}
			reader.ReadObjectEnd();

			if (locStringDictionary == null)
			{
				return LocalizedText.Empty;
			}
			else
			{
				return new LocalizedText(locStringDictionary, this.languageSwitcher);
			}
		}
		private DocumentReferenceCollection<DocumentT> ReadDocumentReferenceCollection<DocumentT>(Formatters.GameDataReader reader, string schemaIdOrName) where DocumentT : Document
		{
			if (reader.IsNull())
			{
				return DocumentReferenceCollection<DocumentT>.Empty;
			}

			var referenceCollection = default(List<DocumentReference<DocumentT>>);
			var isByIdCollection = reader.Token == Formatters.ReaderToken.BeginObject;

			if (isByIdCollection)
			{
				reader.ReadObjectBegin();
			}
			else
			{
				reader.ReadArrayBegin();
			}
			while (reader.Token != Formatters.ReaderToken.EndOfArray &&
					reader.Token != Formatters.ReaderToken.EndOfObject)
			{
				if (isByIdCollection)
				{
					var _ = reader.ReadMember(); // skip id
				}

				if (reader.IsNull())
				{
					reader.NextToken();
					continue;
				}

				var documentReference = this.ReadDocumentReference<DocumentT>(reader, schemaIdOrName);
				if (documentReference == null)
				{
					continue;
				}

				if (referenceCollection == null) { referenceCollection = new List<DocumentReference<DocumentT>>(5); }
				referenceCollection.Add(documentReference);
			}
			if (isByIdCollection)
			{
				reader.ReadObjectEnd();
			}
			else
			{
				reader.ReadArrayEnd();
			}
			if (referenceCollection == null)
			{
				return DocumentReferenceCollection<DocumentT>.Empty;
			}
			else
			{
				return new DocumentReferenceCollection<DocumentT>(referenceCollection);
			}
		}
		private DocumentReference<DocumentT> ReadDocumentReference<DocumentT>(Formatters.GameDataReader reader, string schemaIdOrName) where DocumentT : Document
		{
			var reference = default(DocumentReference<DocumentT>);
			reader.ReadObjectBegin();
			while (reader.Token != Formatters.ReaderToken.EndOfObject)
			{
				var key = reader.ReadMember();
				if (key == "Id")
				{
					reference = new DocumentReference<DocumentT>(reader.ReadAny(), schemaIdOrName, this.FindDocument);
				}
				else
				{
					reader.SkipAny();
				}
			}

			 // TODO maybe throw exception if reference is null (broken)?

			reader.ReadObjectEnd();
			return reference;
		}

		#endregion // Read Game Data
		#region Merge Game Data

		public Formatters.IndexedDictionary<string, object> MergeGameData(IReadOnlyDictionary<string, object> gameDataDocument, IReadOnlyDictionary<string, object> patchDocument)
		{
			gameDataDocument.TryGetValue("Collections", out var gameDataCollectionsObj);
			var gameDataCollections = gameDataCollectionsObj as IReadOnlyDictionary<string, object> ?? new Formatters.IndexedDictionary<string,object>();
			patchDocument.TryGetValue("Collections", out var patchCollectionsObj);
			var patchCollections = patchCollectionsObj as IReadOnlyDictionary<string, object> ?? new Formatters.IndexedDictionary<string,object>();

			var newGameDataDocument = new Formatters.IndexedDictionary<string, object>(gameDataDocument);
			var newCollections = new Formatters.IndexedDictionary<string, object>(gameDataCollections);

			var visitedSchemas = new HashSet<string>(StringComparer.Ordinal);
			foreach (var schemaName in gameDataCollections.Keys.Concat(patchCollections.Keys))
			{
				if (visitedSchemas.Contains(schemaName)) {
					continue; // already has been visited
				}

				var gameDataDocumentCollection = default(object);
				var patchDocumentCollection = default(object);
#pragma warning disable 1522 // Empty switch block
				switch (schemaName)
				{
					case "55a4f32faca22e191098f3d9":
					case "ProjectSettings":
						visitedSchemas.Add("55a4f32faca22e191098f3d9");
						visitedSchemas.Add("ProjectSettings");

						if (!gameDataCollections.TryGetValue("55a4f32faca22e191098f3d9", out gameDataDocumentCollection)) {
							gameDataCollections.TryGetValue("ProjectSettings", out gameDataDocumentCollection);
						}
						if (!patchCollections.TryGetValue("55a4f32faca22e191098f3d9", out patchDocumentCollection)) {
							patchCollections.TryGetValue("ProjectSettings", out patchDocumentCollection);
						}

						if (gameDataDocumentCollection == null || patchDocumentCollection == null)
						{
							newCollections["ProjectSettings"] = gameDataDocumentCollection ?? patchDocumentCollection;
						}
						else
						{
							newCollections["ProjectSettings"] = MergeDocumentCollection<ProjectSetting>(gameDataDocumentCollection, patchDocumentCollection, purgeRest: false);
						}
						break;
				}
#pragma warning restore 1522

			}

			var changeNumber = 0;
			if (gameDataDocument.TryGetValue("ChangeNumber", out var gameDataChangeNumberObj) &&
				gameDataChangeNumberObj != null) {
				changeNumber = Convert.ToInt32(gameDataChangeNumberObj, CultureInfo.InvariantCulture);
			}
			if (patchDocument.TryGetValue("ChangeNumber", out var patchChangeNumberObj) &&
				patchChangeNumberObj != null) {
				changeNumber = Convert.ToInt32(patchChangeNumberObj, CultureInfo.InvariantCulture);
			}

			var revisionHash = default(string);
			if (gameDataDocument.TryGetValue("RevisionHash", out var gameDataRevisionHashObj) &&
				gameDataRevisionHashObj != null) {
				revisionHash = Convert.ToString(gameDataRevisionHashObj, CultureInfo.InvariantCulture);
			}
			if (patchDocument.TryGetValue("RevisionHash", out var patchRevisionHashObj) &&
				patchRevisionHashObj != null) {
				revisionHash = Convert.ToString(patchRevisionHashObj, CultureInfo.InvariantCulture);
			}

			newGameDataDocument["RevisionHash"] = revisionHash;
			newGameDataDocument["ChangeNumber"] = changeNumber;
			newGameDataDocument["Collections"] = newCollections;

			return newGameDataDocument;
		}

		public object MergeDocumentCollection<DocumentT>(object originalDocumentCollection, object modifiedDocumentCollection, bool purgeRest)
		{
			if (modifiedDocumentCollection == null && !purgeRest)
			{
				return Array.Empty<object>();
			}

			var originalCollectionById = ToDocumentsById(originalDocumentCollection);
			var modifiedCollectionById = ToDocumentsById(modifiedDocumentCollection);
			var mergedCollection = new Formatters.IndexedDictionary<string, object>(Math.Max(originalCollectionById.Count, modifiedCollectionById.Count) + 5);
			var documentIds = purgeRest ? modifiedCollectionById.Keys : originalCollectionById.Keys.Union(modifiedCollectionById.Keys);

			foreach (var documentId in documentIds)
			{
				var originalValueExists = originalCollectionById.TryGetValue(documentId, out var originalValue);
				var modifiedValueExists = modifiedCollectionById.TryGetValue(documentId, out var modifiedValue);

				object mergedDocument;
				if (originalValueExists && !modifiedValueExists)
				{
					// unchanged
					mergedDocument = originalValue;
				}
				else if (originalValueExists && originalValue == null)
				{
 					// keep deleted documents as deleted
					mergedDocument = null;
				}
				else if (!originalValueExists && modifiedValueExists)
				{
					// modified
					mergedDocument = modifiedValue;
				}
				else if (originalValue is IReadOnlyDictionary<string, object> originalValueDocument &&
						modifiedValue is IReadOnlyDictionary<string, object> modifiedValueDocument)
				{
					// merged
					mergedDocument = MergeDocument<DocumentT>(originalValueDocument, modifiedValueDocument);
				}
				else
				{
					// modified
					mergedDocument = modifiedValue;
				}

				mergedCollection[documentId] = mergedDocument;
			}
			return mergedCollection;
		}

		public object MergeDocument<DocumentT>(IReadOnlyDictionary<string, object> originalDocument, IReadOnlyDictionary<string, object> modifiedDocument)
		{
			var mergedDocument = new Formatters.IndexedDictionary<string, object>(Math.Max(originalDocument.Count, modifiedDocument.Count) + 5);

			if (typeof(DocumentT) == typeof(ProjectSetting))
			{
				MergePropertyValue<object>(mergedDocument, originalDocument, modifiedDocument, "Id");
				MergePropertyValue<object>(mergedDocument, originalDocument, modifiedDocument, "Name");
				MergePropertyValue<object>(mergedDocument, originalDocument, modifiedDocument, "PrimaryLanguage");
				MergePropertyLanguagesValue(mergedDocument, originalDocument, modifiedDocument, "Languages");
				MergePropertyValue<object>(mergedDocument, originalDocument, modifiedDocument, "Copyright");
				MergePropertyValue<object>(mergedDocument, originalDocument, modifiedDocument, "Version");
				MergePropertyValue<object>(mergedDocument, originalDocument, modifiedDocument, "Extensions");
			}
			return mergedDocument;
		}


		private static void MergePropertyDocumentValue<ValueT>(Formatters.IndexedDictionary<string, object> mergedDocument, IReadOnlyDictionary<string, object> originalDocument, IReadOnlyDictionary<string, object> modifiedDocument, string propertyName, Func<ValueT, ValueT, object> mergeFunc = null)
		{
			if (mergedDocument == null) throw new ArgumentNullException(nameof(mergedDocument));
			if (originalDocument == null) throw new ArgumentNullException(nameof(originalDocument));
			if (modifiedDocument == null) throw new ArgumentNullException(nameof(modifiedDocument));

			originalDocument.TryGetValue(propertyName, out var originalValue);
			modifiedDocument.TryGetValue(propertyName, out var modifiedValue);

			if (originalValue == null &&
				modifiedDocument is IReadOnlyDictionary<string, object> document &&
				!document.ContainsKey("Id"))
			{
				// unable to merge into missing document
				mergedDocument[propertyName] = null;
				return;
			}

			MergePropertyValue<ValueT>(mergedDocument, originalDocument, modifiedDocument, propertyName, mergeFunc);
		}

		private static void MergePropertyLanguagesValue(Formatters.IndexedDictionary<string, object> mergedDocument, IReadOnlyDictionary<string, object> originalDocument, IReadOnlyDictionary<string, object> modifiedDocument, string propertyName)
		{
			if (mergedDocument == null) throw new ArgumentNullException(nameof(mergedDocument));
			if (originalDocument == null) throw new ArgumentNullException(nameof(originalDocument));
			if (modifiedDocument == null) throw new ArgumentNullException(nameof(modifiedDocument));
			if (propertyName == null) throw new ArgumentNullException(nameof(propertyName));

			var originalValueExists = originalDocument.TryGetValue(propertyName, out var originalValue);
			var modifiedValueExists = modifiedDocument.TryGetValue(propertyName, out var modifiedValue);

			if (!originalValueExists && !modifiedValueExists)
			{
				return; // nothing to merge
			}

			var originalLanguages = (originalValue as string ?? "").Split(";,| ".ToCharArray(), StringSplitOptions.RemoveEmptyEntries);
			var modifiedLanguages = (modifiedValue as string ?? "").Split(";,| ".ToCharArray(), StringSplitOptions.RemoveEmptyEntries);

			mergedDocument[propertyName] = string.Join(",", System.Linq.Enumerable.Union(originalLanguages, modifiedLanguages));
		}

		private static void MergePropertyValue<ValueT>(Formatters.IndexedDictionary<string, object> mergedDocument, IReadOnlyDictionary<string, object> originalDocument, IReadOnlyDictionary<string, object> modifiedDocument, string propertyName, Func<ValueT, ValueT, object> mergeFunc = null)
		{
			if (mergedDocument == null) throw new ArgumentNullException(nameof(mergedDocument));
			if (originalDocument == null) throw new ArgumentNullException(nameof(originalDocument));
			if (modifiedDocument == null) throw new ArgumentNullException(nameof(modifiedDocument));
			if (propertyName == null) throw new ArgumentNullException(nameof(propertyName));

			var originalValueExists = originalDocument.TryGetValue(propertyName, out var originalValue);
			var modifiedValueExists = modifiedDocument.TryGetValue(propertyName, out var modifiedValue);

			if (!originalValueExists && !modifiedValueExists)
			{
				return; // nothing to merge
			}

			object mergedValue;
			if (originalValueExists && !modifiedValueExists)
			{
				// unchanged
				mergedValue = originalValue;
			}
			else if (!originalValueExists && modifiedValueExists)
			{
				// modified
				mergedValue = modifiedValue;
			}
			else if (originalValue is ValueT originalTypedValue &&
					modifiedValue is ValueT modifiedTypedValue)
			{
				// merged
				if (mergeFunc != null)
				{
					mergedValue = mergeFunc(originalTypedValue, modifiedTypedValue);
				}
				else
				{
					mergedValue = modifiedValue;
				}
			}
			else
			{
				// modified
				mergedValue = modifiedValue;
			}

			mergedDocument[propertyName] = mergedValue;
		}

		private static object MergeLocalizedText(IReadOnlyDictionary<string, object> originalLocalizedText, IReadOnlyDictionary<string, object> modifiedLocalizedText)
		{
			if (originalLocalizedText == null && modifiedLocalizedText == null)
			{
				return null;
			}
			else if (originalLocalizedText != null && modifiedLocalizedText == null)
			{
				return null;
			}
			else if (originalLocalizedText == null)
			{
				return modifiedLocalizedText;
			}
			else if (LocalizedTextAreEquals(originalLocalizedText, modifiedLocalizedText))
			{
				return originalLocalizedText;
			}

			var mergedLocalizedText = new Formatters.IndexedDictionary<string, object>();
			foreach (var languageId in originalLocalizedText.Keys.Union(modifiedLocalizedText.Keys))
			{
				if (modifiedLocalizedText.ContainsKey(languageId) == false)
				{
					originalLocalizedText.TryGetValue(languageId, out var originalText);
					mergedLocalizedText[languageId] = originalText;
				}
				else
				{
					modifiedLocalizedText.TryGetValue(languageId, out var modifiedText);
					mergedLocalizedText[languageId] = modifiedText;
				}
			}
			return mergedLocalizedText;
		}

		private static bool LocalizedTextAreEquals(IReadOnlyDictionary<string, object> x, IReadOnlyDictionary<string, object> y)
		{
			if (ReferenceEquals(x, y)) return true;
			if (ReferenceEquals(x, null)) return false;
			if (ReferenceEquals(y, null)) return false;
			if (x.GetType() != y.GetType()) return false;
			if (x.Count != y.Count) return false;

			foreach (var kv in x)
			{
				if (string.Equals(kv.Key, "notes", StringComparison.Ordinal))
				{
					continue;
				}

				var xValue = kv.Value;
				y.TryGetValue(kv.Key, out var yValue);

				if (!string.Equals(xValue as string, yValue as string, StringComparison.Ordinal))
				{
					return false;
				}
			}
			return true;
		}

		public IReadOnlyDictionary<string, object> ToDocumentsById(object gameDataDocumentCollection)
		{
			if (gameDataDocumentCollection is IReadOnlyDictionary<string, object> documentsById)
			{
				return documentsById;
			}
			else if (gameDataDocumentCollection is IReadOnlyList<object> list)
			{
				var newDocumentsById = new Formatters.IndexedDictionary<string, object>(list.Count);
				foreach (var documentObj in list)
				{
					if (documentObj is IReadOnlyDictionary<string, object> document &&
						document.TryGetValue("Id", out var idObj) &&
						idObj != null)
					{
						var idStr = Convert.ToString(idObj, CultureInfo.InvariantCulture);
						newDocumentsById[idStr] = documentObj;
					}
				}
				return newDocumentsById;
			}
			else
			{
				return new Formatters.IndexedDictionary<string, object>();
			}
		}

		#endregion
		#region Visitors
		public void ApplyVisitor(Visitor visitor)
		{
			if (visitor == null) throw new ArgumentNullException("visitor");

			foreach (var document in this.EnumerateRoots())
			{
				visitor.Visit(document);
			}
		}

		public void ResolveAllReferences()
		{
			var dereferencingVisitor = new DereferencingVisitor();
			this.ApplyVisitor(dereferencingVisitor);
		}

		private void FindAllDocuments()
		{
			var findingVisitor = new FindingVisitor();
			this.ApplyVisitor(findingVisitor);

			if (findingVisitor.AllProjectSettings?.Count > 0)
			{
				this.allDocuments.ProjectSettingsList = new DocumentCollection<System.String,ProjectSetting>(findingVisitor.AllProjectSettings, document => document.Id);
			}
		}

		public class Visitor
		{
			#region Visit Methods

			public virtual void Visit(Document document)
			{
				if (document == null) throw new ArgumentNullException(nameof(document));
				if (document is ProjectSetting __ProjectSetting)
				{
					this.Visit(__ProjectSetting);
				}
				else
				{
					throw new ArgumentException($"Unknown document type '{document.GetType()}'.", nameof(document));
				}
			}
			public virtual void Visit(ProjectSetting document)
			{
				if (document == null) throw new ArgumentNullException(nameof(document));
			}
			#endregion
		}

		private class FindingVisitor : Visitor
		{
			public List<ProjectSetting> AllProjectSettings;
			#region Visit Methods

			public override void Visit(ProjectSetting document)
			{
				if (this.AllProjectSettings == null)
				{
					this.AllProjectSettings = new List<ProjectSetting>(6);
				}
				this.AllProjectSettings.Add(document);

				base.Visit(document);
			}
			#endregion
		}

		private class DereferencingVisitor : Visitor
		{
			#region Visit Methods

			public override void Visit(ProjectSetting document)
			{
				base.Visit(document);
			}
			#endregion
		}

		#endregion

	}
}
