

//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All


namespace Systems.Charon
{
	using System;
	using System.Linq;
	using System.IO;
	using System.Text;
	using System.Globalization;
	using System.Collections;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.CodeDom.Compiler;
	using System.Runtime.InteropServices;
	using System.Runtime.CompilerServices;
	using System.Linq.Expressions;
	using System.Threading;
	using System.Reflection;
	using System.Diagnostics;


	[Serializable, DebuggerDisplay("LocalizedText, Count: {" + nameof(Count) + "}")]
	public sealed partial class LocalizedText : IReadOnlyDictionary<string, string>
	{
		public static readonly LocalizedText Empty = new LocalizedText(Array.Empty<KeyValuePair<string, string>>(), new LanguageSwitcher());

		private static readonly StringComparer LanguageIdComparer = StringComparer.OrdinalIgnoreCase;

		public sealed class LanguageSwitcher
		{
			public string CurrentLanguageId = "en-US";
			public string FallbackLanguageId = "en-US";
			public string PrimaryLanguageId = "en-US";
			public FallbackOption FallbackOption = FallbackOption.OnNull;
		}

		public enum FallbackOption
		{
			/// <summary>
			///  Fallback when the localized text is null (default)
			/// </summary>
			OnNull,
			/// <summary>
			/// Fallback when the localized text is an empty string
			/// </summary>
			OnEmpty,
			/// <summary>
			/// Fallback when the localized text is not defined in the LocalizedText
			/// </summary>
			OnNotDefined,
		}

		private readonly LanguageSwitcher languageSwitcher;
		private readonly string[] keys;
		private readonly string[] values;
		private string currentValue;
		private string currentValueLanguageId;

		/// <inheritdoc />
		public int Count => this.keys.Length;
		public string Value => this.GetOrUpdateCurrentValue();

		/// <inheritdoc cref="IReadOnlyDictionary{TKey,TValue}.this" />
		public string this[string key]
		{
			get
			{
				var languageIndex = Array.BinarySearch(this.keys, 0, this.keys.Length, key, LanguageIdComparer);
				return languageIndex < 0 ? null : this.values[languageIndex];
			}
		}

		public LocalizedText(IReadOnlyList<KeyValuePair<string, string>> textByLanguageId, LanguageSwitcher languageSwitcher)
		{
			if (textByLanguageId == null) throw new ArgumentNullException(nameof(textByLanguageId));
			if (languageSwitcher == null) throw new ArgumentNullException(nameof(languageSwitcher));

			this.languageSwitcher = languageSwitcher;

			this.keys = new string[textByLanguageId.Count];
			this.values = new string[textByLanguageId.Count];
			for (var i = 0; i < textByLanguageId.Count; i++)
			{
				this.keys[i] = textByLanguageId[i].Key;
				this.values[i] = textByLanguageId[i].Value;
			}
		}

		private string GetOrUpdateCurrentValue()
		{
			var currentLanguageId = this.languageSwitcher.CurrentLanguageId;
			var fallbackLanguageId = this.languageSwitcher.FallbackLanguageId;
			var primaryLanguageId = this.languageSwitcher.PrimaryLanguageId;

			if (currentLanguageId != this.currentValueLanguageId)
			{
				this.currentValueLanguageId = currentLanguageId;
				switch (this.languageSwitcher.FallbackOption)
				{
					case FallbackOption.OnNotDefined:
						if (!this.TryGetValue(currentLanguageId, out this.currentValue) &&
							!this.TryGetValue(fallbackLanguageId, out this.currentValue))
						{
							this.TryGetValue(primaryLanguageId, out this.currentValue);
						}
						this.currentValue = this.currentValue ?? string.Empty;
						break;
					case FallbackOption.OnNull:
						this.currentValue = this[currentLanguageId] ?? this[fallbackLanguageId] ?? this[primaryLanguageId] ?? string.Empty;
						break;
					case FallbackOption.OnEmpty:
						this.currentValue = this[currentLanguageId];
						if (string.IsNullOrEmpty(this.currentValue))
						{
							this.currentValue = this[fallbackLanguageId];
						}
						if (string.IsNullOrEmpty(this.currentValue))
						{
							this.currentValue = this[primaryLanguageId];
						}
						if (string.IsNullOrEmpty(this.currentValue))
						{
							this.currentValue = string.Empty;
						}
						break;
					default: goto case FallbackOption.OnNull;
				}
			}
			return this.currentValue;
		}

		public static implicit operator string(LocalizedText str)
		{
			return str?.Value;
		}

		/// <inheritdoc />
		public override bool Equals(object value)
		{
			var other = value as LocalizedText;
			if (other == null)
			{
				return false;
			}
			else if (ReferenceEquals(this, value))
			{
				return true;
			}
			else if (this.keys.Length != other.keys.Length)
			{
				return false;
			}

			for (var i = 0; i < this.keys.Length; i++)
			{
				if (LanguageIdComparer.Equals(this.keys[i], other.keys[i]) == false)
				{
					return false;
				}

				if (string.Equals(this.values[i], other.values[i], StringComparison.OrdinalIgnoreCase) == false)
				{
					return false;
				}
			}

			return true;
		}

		/// <inheritdoc />
		public override int GetHashCode()
		{
			var hashCode = 0;
			foreach (var value in this.values)
			{
				hashCode += unchecked((value ?? "").GetHashCode());
			}
			return hashCode;
		}

		/// <inheritdoc />
		IEnumerable<string> IReadOnlyDictionary<string, string>.Keys => this.keys;
		/// <inheritdoc />
		IEnumerable<string> IReadOnlyDictionary<string, string>.Values => this.values;

		/// <inheritdoc />
		bool IReadOnlyDictionary<string, string>.TryGetValue(string key, out string value)
		{
			return ((IReadOnlyDictionary<string, string>)this).TryGetValue(key, out value);
		}
		/// <inheritdoc />
		bool IReadOnlyDictionary<string, string>.ContainsKey(string key)
		{
			return ((IReadOnlyDictionary<string, string>)this).ContainsKey(key);
		}

		public bool TryGetValue(string key, out string value)
		{
			var languageIndex = Array.BinarySearch(this.keys, 0, this.keys.Length, key, LanguageIdComparer);
			if (languageIndex >= 0)
			{
				value = this.values[languageIndex];
				return value != null;
			}
			else
			{
				value = null;
				return false;
			}
		}

		/// <inheritdoc />
		IEnumerator<KeyValuePair<string, string>> IEnumerable<KeyValuePair<string, string>>.GetEnumerator()
		{
			for (var i = 0; i < this.keys.Length; i++)
			{
				yield return new KeyValuePair<string, string>(this.keys[i], this.values[i]);
			}
		}
		/// <inheritdoc />
		System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
		{
			for (var i = 0; i < this.keys.Length; i++)
			{
				yield return new KeyValuePair<string, string>(this.keys[i], this.values[i]);
			}
		}

		public static bool operator ==(LocalizedText value1, LocalizedText value2)
		{
			return Equals(value1, value2);
		}
		public static bool operator !=(LocalizedText value1, LocalizedText value2)
		{
			return Equals(value1, value2) == false;
		}

		public override string ToString()
		{
			return this.Value;
		}
	}

}
