

//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All


namespace Systems.Charon
{
	using System;
	using System.Linq;
	using System.IO;
	using System.Text;
	using System.Globalization;
	using System.Collections;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.CodeDom.Compiler;
	using System.Runtime.InteropServices;
	using System.Runtime.CompilerServices;
	using System.Linq.Expressions;
	using System.Threading;
	using System.Reflection;
	using System.Diagnostics;

	/// <summary>
	/// Project Settings with Text id. Settings.
	/// </summary>
	[GeneratedCode(GameData.GeneratorName, GameData.GeneratorVersion)]
	public sealed partial class ProjectSetting : Document, IEquatable<ProjectSetting>, IComparable, IComparable<ProjectSetting>
	{
		public static readonly string SchemaId = "55a4f32faca22e191098f3d9";
		public static readonly string SchemaName = "ProjectSettings";

		private readonly int hashCode;

		/// <summary>
		/// Id property of Text type. Not Empty, Unique.
		/// </summary>
		public System.String Id { get; }
		/// <summary>
		/// Project Name property of Text type. Not Null.
		/// </summary>
		public System.String Name { get; }
		/// <summary>
		/// Primary Language property of Text type. Can Be Null.
		/// </summary>
		public System.String PrimaryLanguage { get; }
		/// <summary>
		/// Languages property of Text type. Can Be Null.
		/// </summary>
		public System.String Languages { get; }
		/// <summary>
		/// Copyright property of Text type. Can Be Null.
		/// </summary>
		public System.String Copyright { get; }
		/// <summary>
		/// Version property of Text type. Not Empty.
		/// </summary>
		public System.String Version { get; }
		/// <summary>
		/// Extensions property of Text type. Can Be Null.
		/// </summary>
		public System.String Extensions { get; }
		/// <summary>
		/// Constructor for ProjectSetting.
		/// </summary>
		public ProjectSetting(System.String id, System.String name, System.String primaryLanguage, System.String languages, System.String copyright, System.String version, System.String extensions)
		{
			this.OnBeforeInitialize();
			this.Id = id;
			this.Name = name;
			this.PrimaryLanguage = primaryLanguage;
			this.Languages = languages;
			this.Copyright = copyright;
			this.Version = version;
			this.Extensions = extensions;
			this.hashCode = this.ComputeHashCode();
			this.OnInitialize();
		}

		partial void OnBeforeInitialize();
		partial void OnInitialize();

		/// <inheritdoc />
		public bool Equals(ProjectSetting other)
		{
			return this.Equals((object)other);
		}
		/// <inheritdoc />
		public override bool Equals(object value)
		{
			if (value is ProjectSetting == false)
			{
				return false;
			}
			else if (ReferenceEquals(this, value))
			{
				return true;
			}
			else if (ReferenceEquals(value, null))
			{
				return false;
			}

			var other = (ProjectSetting)value;
			return (this.GetHashCode() == other.GetHashCode()
				&& AreEquals(this.Id, other.Id)
				&& AreEquals(this.Name, other.Name)
				&& AreEquals(this.PrimaryLanguage, other.PrimaryLanguage)
				&& AreEquals(this.Languages, other.Languages)
				&& AreEquals(this.Copyright, other.Copyright)
				&& AreEquals(this.Version, other.Version)
				&& AreEquals(this.Extensions, other.Extensions)
			);
		}
		/// <inheritdoc />
		public override int GetHashCode()
		{
			return this.hashCode;
		}

		/// <inheritdoc />
		int IComparable.CompareTo(object obj)
		{
			return this.CompareTo(obj as ProjectSetting);
		}
		/// <inheritdoc />
		public int CompareTo(ProjectSetting other)
		{
			if (ReferenceEquals(other, null))
			{
				return 1;
			}
			return string.Compare(this.Id, other.Id, StringComparison.Ordinal);
		}

		public static bool operator ==(ProjectSetting value1, ProjectSetting value2)
		{
			return Equals(value1, value2);
		}
		public static bool operator !=(ProjectSetting value1, ProjectSetting value2)
		{
			return Equals(value1, value2) == false;
		}

		private int ComputeHashCode()
		{
			return unchecked(this.GetType().Name.GetHashCode()
				+ GetHashCodeFor(this.Id)
				+ GetHashCodeFor(this.Name)
				+ GetHashCodeFor(this.PrimaryLanguage)
				+ GetHashCodeFor(this.Languages)
				+ GetHashCodeFor(this.Copyright)
				+ GetHashCodeFor(this.Version)
				+ GetHashCodeFor(this.Extensions)
			);
		}

		/// <inheritdoc />
		public override string ToString()
		{
			var sb = new System.Text.StringBuilder();
				sb.Append("Id: ").Append(this.Id).Append(", ");
				sb.Append("Project Name: ").Append(this.Name).Append(", ");
				sb.Append("Primary Language: ").Append(this.PrimaryLanguage).Append(", ");
				sb.Append("Languages: ").Append(this.Languages).Append(", ");
				sb.Append("Copyright: ").Append(this.Copyright).Append(", ");
				sb.Append("Version: ").Append(this.Version).Append(", ");
				sb.Append("Extensions: ").Append(this.Extensions).Append(", ");

			if (sb.Length > 2)
			{
				sb.Length -= 2;
			}
			return sb.ToString();
		}
	}
}
