

//
// The source code was generated by the Charon, GameDevWare, 2025
// License: MIT
//
//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All


namespace Systems.Charon
{
	using System;
	using System.Linq;
	using System.IO;
	using System.Text;
	using System.Globalization;
	using System.Collections;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.CodeDom.Compiler;
	using System.Runtime.InteropServices;
	using System.Runtime.CompilerServices;
	using System.Linq.Expressions;
	using System.Threading;
	using System.Reflection;
	using System.Diagnostics;

	/// <summary>
	/// Test Schema with Text id.
	/// </summary>
	[GeneratedCode(GameData.GeneratorName, GameData.GeneratorVersion)]
	public sealed partial class TestSchema : Document, IEquatable<TestSchema>, IComparable, IComparable<TestSchema>
	{
		public static readonly string SchemaId = "692742cf6f67fb0ad0adfa60";
		public static readonly string SchemaName = "TestSchema";

		private readonly int hashCode;

		/// <summary>
		/// Id property of Text type. Not Empty, Unique.
		/// </summary>
		public System.String Id { get; }
		/// <summary>
		/// Value property of Text type. Not Null.
		/// </summary>
		public System.String Value { get; }
		/// <summary>
		/// Number property of Number type. Not Null.
		/// </summary>
		public System.Single Number { get; }
		/// <summary>
		/// Constructor for TestSchema.
		/// </summary>
		public TestSchema(System.String id, System.String @value, System.Single number)
		{
			this.OnBeforeInitialize();
			this.Id = id;
			this.Value = @value;
			this.Number = number;
			this.hashCode = this.ComputeHashCode();
			this.OnInitialize();
		}

		partial void OnBeforeInitialize();
		partial void OnInitialize();


		/// <inheritdoc />
		public bool Equals(TestSchema other)
		{
			return this.Equals((object)other);
		}
		/// <inheritdoc />
		public override bool Equals(object value)
		{
			if (value is TestSchema == false)
			{
				return false;
			}
			else if (ReferenceEquals(this, value))
			{
				return true;
			}
			else if (ReferenceEquals(value, null))
			{
				return false;
			}

			var other = (TestSchema)value;
			return (this.GetHashCode() == other.GetHashCode()
				&& AreEquals(this.Id, other.Id)
				&& AreEquals(this.Value, other.Value)
				&& AreEquals(this.Number, other.Number)
			);
		}
		/// <inheritdoc />
		public override int GetHashCode()
		{
			return this.hashCode;
		}

		/// <inheritdoc />
		int IComparable.CompareTo(object obj)
		{
			return this.CompareTo(obj as TestSchema);
		}
		/// <inheritdoc />
		public int CompareTo(TestSchema other)
		{
			if (ReferenceEquals(other, null))
			{
				return 1;
			}
			return string.Compare(this.Id, other.Id, StringComparison.Ordinal);
		}

		public static bool operator ==(TestSchema value1, TestSchema value2)
		{
			return Equals(value1, value2);
		}
		public static bool operator !=(TestSchema value1, TestSchema value2)
		{
			return Equals(value1, value2) == false;
		}

		private int ComputeHashCode()
		{
			return unchecked(this.GetType().Name.GetHashCode()
				+ GetHashCodeFor(this.Id)
				+ GetHashCodeFor(this.Value)
				+ GetHashCodeFor(this.Number)
			);
		}

		/// <inheritdoc />
		public override string ToString()
		{
			var sb = new System.Text.StringBuilder();
				sb.Append("Id: ").Append(this.Id).Append(", ");
				sb.Append("Value: ").Append(this.Value).Append(", ");
				sb.Append("Number: ").Append(this.Number).Append(", ");

			if (sb.Length > 2)
			{
				sb.Length -= 2;
			}
			return sb.ToString();
		}
	}
}
